### ISSUE TITLE
Mis-applied tardiff

### ISSUE THREAD

**Issue by owtaylor** [containers/tar-diff#2]
Found an example of tars that don't diff and patch correctly

``` sh
$ curl -O https://fishsoup.net/misc/ubi8-8.0-129.tar.gz
$ curl -O https://fishsoup.net/misc/ubi8-8.0-154.tar.gz
$ tar-diff ubi8-8.0-129.tar.gz ubi8-8.0-154.tar.gz ubi8 .tardiff
$ mkdir ubi8-8.0-129
$ tar -C ubi8-8.0-129 -xf ubi8-8.0-129.tar.gz 
$ tar-patch ubi8.tardiff ubi8-8.0-129 ubi8-8.0-154-reconstructed.tar
$ zcat  ubi8-8.0-154.tar.gz | sha256sum
25311323356d6a4a125dd592d8827054a9d14ef8e161ea2c073571a087346013
$ sha256sum ubi8-8.0-154-reconstructed.tar
6d25ba633a6297a61b001d3340bc92b6dd1938b0caf8c56686885402071822f2
```
 * The reconstructed tar file has the right number of bytes
 * It unpacks into a file system tree with the right files, and the right size and permissions
 * The contents of two files are wrong:
   -  `usr/lib64/python3.6/__pycache__/_pydecimal.cpython-36.pyc`
   - `usr/lib64/python3.6/__pycache__/gettext.cpython-36.pyc`
 * If you repack the tarballs with GNU tar or libarchive's bsdtar, the problem doesn't occur

All a bit mysterious! :-)

**Comment by alexlarsson** [comment]
This is fixed in master, i think it was https://github.com/containers/tar-diff/commit/55be8aea7c7c9cb8698334af11a7d18707c7b197
